#pragma once

enum tty_sym
{
    tty_sym_any                = -1,
    tty_sym_none               = 0,
    tty_sym_ns                 = 1,
    tty_sym_flag               = 2,
    tty_sym_code               = 3,
    tty_sym_oper               = 4,
    tty_sym_mod                = 5,
    tty_sym_char               = 6,
    tty_sym_key                = 7,
    tty_sym_string             = 8,
    tty_sym_int                = 9,
};

enum tty_code
{
    tty_code_csi               = 1,
    tty_code_ss2               = 2,
    tty_code_ss3               = 3,
};

enum tty_oper
{
    tty_oper_none              = 0,
    tty_oper_plus              = 1,
    tty_oper_equal             = 2,
    tty_oper_arrow             = 3,
    tty_oper_emit              = 4,
    tty_oper_copy              = 5,
    tty_oper_paste             = 6,
};

enum tty_mod
{
    tty_mod_shift              = 0x1,
    tty_mod_control            = 0x2,
    tty_mod_alt                = 0x4,
    tty_mod_super              = 0x8,
    tty_mod_capslock           = 0x10,
    tty_mod_numlock            = 0x20,
};

enum tty_key
{
    tty_key_space              = 32,
    tty_key_apostrophe         = 39,
    tty_key_comma              = 44,
    tty_key_minus              = 45,
    tty_key_period             = 46,
    tty_key_slash              = 47,
    tty_key_0                  = 48,
    tty_key_1                  = 49,
    tty_key_2                  = 50,
    tty_key_3                  = 51,
    tty_key_4                  = 52,
    tty_key_5                  = 53,
    tty_key_6                  = 54,
    tty_key_7                  = 55,
    tty_key_8                  = 56,
    tty_key_9                  = 57,
    tty_key_semicolon          = 59,
    tty_key_equal              = 61,
    tty_key_a                  = 65,
    tty_key_b                  = 66,
    tty_key_c                  = 67,
    tty_key_d                  = 68,
    tty_key_e                  = 69,
    tty_key_f                  = 70,
    tty_key_g                  = 71,
    tty_key_h                  = 72,
    tty_key_i                  = 73,
    tty_key_j                  = 74,
    tty_key_k                  = 75,
    tty_key_l                  = 76,
    tty_key_m                  = 77,
    tty_key_n                  = 78,
    tty_key_o                  = 79,
    tty_key_p                  = 80,
    tty_key_q                  = 81,
    tty_key_r                  = 82,
    tty_key_s                  = 83,
    tty_key_t                  = 84,
    tty_key_u                  = 85,
    tty_key_v                  = 86,
    tty_key_w                  = 87,
    tty_key_x                  = 88,
    tty_key_y                  = 89,
    tty_key_z                  = 90,
    tty_key_left_bracket       = 91,
    tty_key_backslash          = 92,
    tty_key_right_bracket      = 93,
    tty_key_grave_accent       = 96,
    tty_key_world_1            = 161,
    tty_key_world_2            = 162,
    tty_key_escape             = 256,
    tty_key_enter              = 257,
    tty_key_tab                = 258,
    tty_key_backspace          = 259,
    tty_key_insert             = 260,
    tty_key_delete             = 261,
    tty_key_right              = 262,
    tty_key_left               = 263,
    tty_key_down               = 264,
    tty_key_up                 = 265,
    tty_key_page_up            = 266,
    tty_key_page_down          = 267,
    tty_key_home               = 268,
    tty_key_end                = 269,
    tty_key_caps_lock          = 280,
    tty_key_scroll_lock        = 281,
    tty_key_num_lock           = 282,
    tty_key_print_screen       = 283,
    tty_key_pause              = 284,
    tty_key_f1                 = 290,
    tty_key_f2                 = 291,
    tty_key_f3                 = 292,
    tty_key_f4                 = 293,
    tty_key_f5                 = 294,
    tty_key_f6                 = 295,
    tty_key_f7                 = 296,
    tty_key_f8                 = 297,
    tty_key_f9                 = 298,
    tty_key_f10                = 299,
    tty_key_f11                = 300,
    tty_key_f12                = 301,
    tty_key_f13                = 302,
    tty_key_f14                = 303,
    tty_key_f15                = 304,
    tty_key_f16                = 305,
    tty_key_f17                = 306,
    tty_key_f18                = 307,
    tty_key_f19                = 308,
    tty_key_f20                = 309,
    tty_key_f21                = 310,
    tty_key_f22                = 311,
    tty_key_f23                = 312,
    tty_key_f24                = 313,
    tty_key_f25                = 314,
    tty_key_pad_0              = 320,
    tty_key_pad_1              = 321,
    tty_key_pad_2              = 322,
    tty_key_pad_3              = 323,
    tty_key_pad_4              = 324,
    tty_key_pad_5              = 325,
    tty_key_pad_6              = 326,
    tty_key_pad_7              = 327,
    tty_key_pad_8              = 328,
    tty_key_pad_9              = 329,
    tty_key_pad_decimal        = 330,
    tty_key_pad_divide         = 331,
    tty_key_pad_multiply       = 332,
    tty_key_pad_subtract       = 333,
    tty_key_pad_add            = 334,
    tty_key_pad_enter          = 335,
    tty_key_pad_equal          = 336,
    tty_key_left_shift         = 340,
    tty_key_left_control       = 341,
    tty_key_left_alt           = 342,
    tty_key_left_super         = 343,
    tty_key_right_shift        = 344,
    tty_key_right_control      = 345,
    tty_key_right_alt          = 346,
    tty_key_right_super        = 347,
    tty_key_menu               = 384,
};

struct tty_keypress { int key; int mods; };
struct tty_translate_result { int oper; std::string data; };

void tty_keymap_init(std::vector<char> &input);
void tty_keymap_dump();
tty_translate_result tty_keymap_translate(std::vector<tty_keypress> seq, int flags);
std::string tty_keymap_mod_name(int mod);
std::string tty_keymap_key_name(int key);
